# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

jobs:

- job: Windows

  pool:
    vmImage: 'windows-2022'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - script: |
      git submodule update --init --recursive
  - script: |
      dist.deploy.bat
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\bin\$(BuildConfiguration)\**\tests.dll
        **\bin\$(BuildConfiguration)\**\tests.JexusManager.dll
        !**\obj\**
        !**\xunit.runner.visualstudio.testadapter.dll
        !**\xunit.runner.visualstudio.dotnetcore.testadapter.dll
      runInParallel: false